### ISSUE TITLE
35.1 1920x1200@30fps Support

### ISSUE THREAD

**Issue by EmbeddedDesign** [LPXingxing/LI-AR0234CS-STEREO-GMSL2#4]
The documentation for 35.1 says:

> This driver supports 1920x1200@30fps,1920x1200@60fps, 960x600@120fps

However, nvgstcapture reports:
```
GST_ARGUS: Available Sensor modes :
GST_ARGUS: 1920 x 1200 FR = 59.999999 fps Duration = 16666667 ; Analog Gain range min 1.000000, max 16.000000; Exposure Range min 28000, max 13000000;
GST_ARGUS: 960 x 600 FR = 120.000005 fps Duration = 8333333 ; Analog Gain range min 1.000000, max 16.000000; Exposure Range min 28000, max 22000000;
```
Is 1920x1200@30fps mode supported?

**Comment by LPXingxing** [comment]
Yes. It can support 30fps. you use set frame rate option to get 30fps.

Also using argus_camera to get 30fps

在 2022/11/24 8:48, Operator 写道:

**Comment by EmbeddedDesign** [comment]
Can confirm that, while it does not show as being natively supported, setting the frameraate parameter of argus to 30fps does indeed seem to work fine.
